# -*- coding: utf-8 -*-
"""bubble.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-rd0hBgI73fQiEB6fqAmsg4oeK7kg6K1
"""

#@title Installation of Libraries
!pip install yfinance pandas numpy matplotlib plotly -q

#@title Bubble Detection
# IMPORT LIBRARIES
# =============================================================================
import yfinance as yf
import pandas as pd
import numpy as np
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import plotly.express as px
from datetime import datetime, timedelta
import warnings
warnings.filterwarnings('ignore')

print("✅ Libraries imported successfully!")

# =============================================================================
# BUBBLE DETECTION FUNCTIONS
# =============================================================================

def get_stock_data(ticker, period="5y"):
    """Get stock data from Yahoo Finance"""
    try:
        stock = yf.Ticker(ticker)
        data = stock.history(period=period)
        if data.empty:
            print(f"❌ No data found for {ticker}")
            return None
        return data
    except Exception as e:
        print(f"❌ Error fetching data for {ticker}: {e}")
        return None

def calculate_bubble_metrics(data):
    """Calculate metrics for bubble detection"""

    # Calculate returns
    data['Returns'] = data['Close'].pct_change()

    # Calculate rolling metrics
    data['Rolling_20D_Return'] = data['Close'].pct_change(20)
    data['Rolling_50D_Return'] = data['Close'].pct_change(50)
    data['Rolling_Volatility'] = data['Returns'].rolling(20).std() * np.sqrt(252)

    # Price relative to moving averages
    data['SMA_50'] = data['Close'].rolling(50).mean()
    data['SMA_200'] = data['Close'].rolling(200).mean()
    data['Price_SMA50_Ratio'] = data['Close'] / data['SMA_50']
    data['Price_SMA200_Ratio'] = data['Close'] / data['SMA_200']

    # Exponential growth detection
    data['Log_Price'] = np.log(data['Close'])
    data['Log_Returns'] = data['Log_Price'].diff()

    return data.dropna()

def identify_bubble_periods(data, threshold=2.0):
    """Identify potential bubble periods"""
    bubble_periods = []

    # Criteria for bubble detection
    high_return_periods = data['Rolling_20D_Return'] > 0.15  # 15% in 20 days
    high_valuation = data['Price_SMA50_Ratio'] > 1.3  # 30% above 50-day MA
    high_volatility = data['Rolling_Volatility'] > 0.4  # 40% annualized volatility

    bubble_mask = high_return_periods & high_valuation & high_volatility

    if bubble_mask.any():
        bubble_dates = data[bubble_mask].index
        # Group consecutive bubble dates
        for date in bubble_dates:
            if not bubble_periods or (date - bubble_periods[-1][1]).days > 30:
                bubble_periods.append((date, date))
            else:
                bubble_periods[-1] = (bubble_periods[-1][0], date)

    return bubble_periods

def get_ticker_descriptions(tickers):
    """Get descriptions for tickers"""
    descriptions = {}
    common_descriptions = {
        # Stocks
        "AAPL": "Apple - Technology",
        "MSFT": "Microsoft - Technology",
        "GOOG": "Google - Technology",
        "GOOGL": "Google - Technology",
        "AMZN": "Amazon - E-commerce & Cloud",
        "NVDA": "NVIDIA - AI & Semiconductors",
        "TSLA": "Tesla - Electric Vehicles",
        "META": "Meta - Social Media",
        "BRK-B": "Berkshire Hathaway - Conglomerate",
        "JPM": "JPMorgan Chase - Banking",
        "JNJ": "Johnson & Johnson - Healthcare",
        "V": "Visa - Payments",
        "PG": "Procter & Gamble - Consumer Goods",
        "UNH": "UnitedHealth - Healthcare",
        "HD": "Home Depot - Retail",

        # Cryptocurrencies
        "BTC-USD": "Bitcoin - Cryptocurrency",
        "ETH-USD": "Ethereum - Cryptocurrency",
        "ADA-USD": "Cardano - Cryptocurrency",
        "DOT-USD": "Polkadot - Cryptocurrency",
        "DOGE-USD": "Dogecoin - Cryptocurrency",
        "SOL-USD": "Solana - Cryptocurrency",
        "XRP-USD": "Ripple - Cryptocurrency",

        # ETFs
        "SPY": "SPDR S&P 500 ETF",
        "QQQ": "Invesco QQQ Trust",
        "IWM": "iShares Russell 2000 ETF",
        "GLD": "SPDR Gold Shares",
        "TLT": "iShares 20+ Year Treasury Bond ETF",

        # Meme Stocks
        "GME": "GameStop - Meme Stock",
        "AMC": "AMC Entertainment - Meme Stock",
        "BB": "BlackBerry - Meme Stock"
    }

    for ticker in tickers:
        if ticker in common_descriptions:
            descriptions[ticker] = common_descriptions[ticker]
        else:
            # Try to get info from yfinance for unknown tickers
            try:
                stock = yf.Ticker(ticker)
                info = stock.info
                company_name = info.get('longName', info.get('shortName', 'Unknown Company'))
                industry = info.get('industry', 'Unknown Industry')
                descriptions[ticker] = f"{company_name} - {industry}"
            except:
                descriptions[ticker] = f"{ticker} - Stock/Crypto Analysis"

    return descriptions

# =============================================================================
# USER INPUT FOR TICKERS
# =============================================================================

print("\n🚀 BUBBLE PATTERN ANALYSIS")
print("=" * 50)

# Get user input for tickers
def get_user_tickers():
    print("\n📈 Enter ticker symbols (separated by commas):")
    print("Examples: NVDA, TSLA, GOOG, BTC-USD, AAPL, GME")
    print("Or press Enter to use default tickers")

    user_input = input("\nEnter tickers: ").strip().upper()

    if user_input == "":
        # Default tickers if user presses Enter
        default_tickers = ["NVDA", "TSLA", "GOOG", "BTC-USD"]
        print(f"Using default tickers: {', '.join(default_tickers)}")
        return default_tickers
    else:
        # Process user input
        tickers = [ticker.strip() for ticker in user_input.split(',')]
        tickers = [ticker for ticker in tickers if ticker]  # Remove empty strings
        return tickers

# Get tickers from user
current_tickers = get_user_tickers()

if not current_tickers:
    print("❌ No valid tickers entered. Using default tickers.")
    current_tickers = ["NVDA", "TSLA", "GOOG", "BTC-USD"]

print(f"\n✅ Analyzing {len(current_tickers)} tickers: {', '.join(current_tickers)}")

# Get descriptions for the tickers
ticker_descriptions = get_ticker_descriptions(current_tickers)

# =============================================================================
# BUBBLE ANALYSIS
# =============================================================================

# Create comprehensive bubble analysis dashboard
for ticker in current_tickers:
    description = ticker_descriptions.get(ticker, f"{ticker} - Analysis")
    print(f"\n📊 Analyzing {ticker}: {description}")

    try:
        # Get data with appropriate period
        if ticker in ["BTC-USD", "ETH-USD", "ADA-USD"] or "USD" in ticker:
            # Cryptocurrencies - use longer period
            data = get_stock_data(ticker, "5y")
        else:
            # Stocks - use 3 years
            data = get_stock_data(ticker, "3y")

        if data is None:
            continue

        data = calculate_bubble_metrics(data)
        bubble_periods = identify_bubble_periods(data)

        # Create subplots for comprehensive bubble analysis
        fig = make_subplots(
            rows=3, cols=1,
            subplot_titles=[
                f'{ticker}: Price with Bubble Periods',
                f'{ticker}: Price vs Moving Averages',
                f'{ticker}: Bubble Risk Score'
            ],
            vertical_spacing=0.08,
            row_heights=[0.4, 0.3, 0.3]
        )

        # 1. TOP: Price with Bubble Periods
        fig.add_trace(
            go.Scatter(
                x=data.index,
                y=data['Close'],
                mode='lines',
                name='Price',
                line=dict(color='blue', width=2)
            ),
            row=1, col=1
        )

        # Highlight bubble periods
        for start_date, end_date in bubble_periods:
            bubble_data = data.loc[start_date:end_date]
            fig.add_trace(
                go.Scatter(
                    x=bubble_data.index,
                    y=bubble_data['Close'],
                    mode='lines',
                    name='Bubble Period',
                    line=dict(color='red', width=4),
                    opacity=0.8,
                    showlegend=False
                ),
                row=1, col=1
            )

        # Add moving averages
        fig.add_trace(
            go.Scatter(
                x=data.index,
                y=data['SMA_50'],
                mode='lines',
                name='SMA 50',
                line=dict(color='orange', width=1, dash='dash')
            ),
            row=1, col=1
        )

        fig.add_trace(
            go.Scatter(
                x=data.index,
                y=data['SMA_200'],
                mode='lines',
                name='SMA 200',
                line=dict(color='green', width=1, dash='dash')
            ),
            row=1, col=1
        )

        # 2. MIDDLE: Price vs Moving Average Ratios
        fig.add_trace(
            go.Scatter(
                x=data.index,
                y=data['Price_SMA50_Ratio'],
                mode='lines',
                name='Price / SMA 50',
                line=dict(color='red', width=2)
            ),
            row=2, col=1
        )

        fig.add_trace(
            go.Scatter(
                x=data.index,
                y=data['Price_SMA200_Ratio'],
                mode='lines',
                name='Price / SMA 200',
                line=dict(color='blue', width=2)
            ),
            row=2, col=1
        )

        # Add overvaluation threshold
        fig.add_hline(y=1.3, line_dash="dash", line_color="red",
                     annotation_text="Overvaluation Threshold",
                     row=2, col=1, opacity=0.7)

        # 3. BOTTOM: Bubble Risk Score (composite metric)
        risk_score = (data['Price_SMA50_Ratio'] - 1) * 100 + data['Rolling_20D_Return'] * 1000 + data['Rolling_Volatility'] * 100
        fig.add_trace(
            go.Scatter(
                x=data.index,
                y=risk_score,
                mode='lines',
                name='Bubble Risk Score',
                line=dict(color='red', width=3)
            ),
            row=3, col=1
        )

        fig.add_hline(y=50, line_dash="dash", line_color="orange",
                     annotation_text="High Risk",
                     row=3, col=1, opacity=0.7)

        fig.update_layout(
            height=900,
            title_text=f"BUBBLE ANALYSIS: {ticker} - {description}",
            showlegend=True
        )

        fig.show()

        # Print bubble analysis summary
        max_return = data['Rolling_20D_Return'].max() * 100
        max_valuation = (data['Price_SMA50_Ratio'].max() - 1) * 100
        current_valuation = (data['Price_SMA50_Ratio'].iloc[-1] - 1) * 100

        print(f"🔍 {ticker} Bubble Analysis:")
        print(f"   • Maximum 20-day return: {max_return:.1f}%")
        print(f"   • Peak overvaluation: {max_valuation:.1f}% above 50-day MA")
        print(f"   • Current overvaluation: {current_valuation:.1f}% above 50-day MA")
        print(f"   • Bubble periods detected: {len(bubble_periods)}")
        for i, (start, end) in enumerate(bubble_periods, 1):
            duration = (end - start).days
            print(f"     Period {i}: {start.strftime('%Y-%m-%d')} to {end.strftime('%Y-%m-%d')} ({duration} days)")

    except Exception as e:
        print(f"❌ Error analyzing {ticker}: {e}")

# =============================================================================
# BUBBLE CHARACTERISTICS SUMMARY
# =============================================================================

print("\n" + "="*70)
print("🚀 BUBBLE PATTERNS - KEY CHARACTERISTICS")
print("="*70)

print("\n🔍 COMMON BUBBLE PATTERNS:")
print("• 📈 Exponential price growth (50-100%+ in weeks)")
print("• 💰 Extreme overvaluation (30%+ above historical averages)")
print("• 🎯 High volatility (40%+ annualized)")
print("• 📰 Media frenzy and public excitement")
print("• 🤝 Social proof and fear of missing out (FOMO)")
print("• ⚠️ Disconnect from fundamentals")

print("\n⚠️ BUBBLE RISK INDICATORS:")
print("• Price > 30% above 50-day moving average")
print("• 20-day returns > 15%")
print("• Volume spikes on price advances")
print("• High put/call ratios (smart money hedging)")
print("• Extreme sentiment readings")

print("\n💡 BUBBLE TRADING INSIGHTS:")
print("• Ride the trend but know your exit strategy")
print("• Use trailing stops to protect gains")
print("• Avoid buying at peak euphoria")
print("• Consider volatility for position sizing")
print("• Monitor breadth and leadership rotation")

print("="*70)

# Current bubble risk assessment
print("\n📈 CURRENT BUBBLE RISK ASSESSMENT:")
try:
    for ticker in current_tickers:
        data = get_stock_data(ticker, "1y")
        if data is None:
            continue

        data = calculate_bubble_metrics(data)

        current_price = data['Close'].iloc[-1]
        sma_50 = data['SMA_50'].iloc[-1]
        overvaluation = (current_price / sma_50 - 1) * 100
        recent_return = data['Rolling_20D_Return'].iloc[-1] * 100

        bubble_risk = "🟢 LOW" if overvaluation < 20 else "🟡 MEDIUM" if overvaluation < 40 else "🔴 HIGH"

        print(f"• {ticker}: {bubble_risk} risk")
        print(f"  Price: ${current_price:.2f} | {overvaluation:+.1f}% vs 50-day MA")
        print(f"  20-day return: {recent_return:+.1f}%")

except Exception as e:
    print(f"• Current assessment unavailable: {e}")

print("\n🎯 Interactive bubble analysis complete!")
print("💡 Use these tools to identify and monitor potential bubble formations!")
print("🔄 Run the code again to analyze different tickers!")